
create table lingua (
	cod_ling int primary key auto_increment,
	nome_ling varchar(15));

insert into lingua(cod_ling,nome_ling)
values
	(1,"Afrikaans"),
	(2,"Albanian"),
	(3,"Arabic"),
	(4,"Azerbaijani"),
	(5,"Bambara"),
	(6,"Bengali"),
	(7,"Bosnian"),
	(8,"Bulgarian"),
	(9,"Cantonese"),
	(10,"Croatian"),
	(11,"Czech"),
	(12,"Danish"),
	(13,"Dutch"),
	(14,"English"),
	(15,"Filipino"),
	(16,"Finnish"),
	(17,"French"),
	(18,"Galician"),
	(19,"Georgian"),
	(20,"German"),
	(21,"Greek"),
	(22,"Guarani"),
	(23,"Hausa"),
	(24,"Hebrew"),
	(25,"Hindi"),
	(26,"Hungarian"),
	(27,"Italian"),
	(28,"Japanese"),
	(29,"Khmer"),
	(30,"Korean"),
	(31,"Kurdish"),
	(32,"Lao"),
	(33,"Latin"),
	(34,"Latvian"),
	(35,"Mandarin"),
	(36,"Maori"),
	(37,"Marathi"),
	(38,"Mongolian"),
	(39,"No Language"),
	(40,"Norwegian"),
	(41,"Persian"),
	(42,"Polish"),
	(43,"Portuguese"),
	(44,"Quechua"),
	(45,"Romanian"),
	(46,"Russian"),
	(47,"Sardinian"),
	(48,"Serbian"),
	(49,"Serbo-Croatian"),
	(50,"Sinhalese"),
	(51,"Slovak"),
	(52,"Spanish"),
	(53,"Swahili"),
	(54,"Swedish"),
	(55,"Tagalog"),
	(56,"Tamil"),
	(57,"Thai"),
	(58,"Turkish"),
	(59,"Vietnamese"),
	(60,"Wolof"),
	(61,"Xhosa"),
	(62,"Yiddish"),
	(63,"Zulu");

