use Cinemao;

create table pais (
	cod_pais int primary key auto_increment,
	nome_pais varchar(50));

insert into pais(cod_pais,nome_pais)
values
	(1,"Algeria"),
	(2,"America"),
	(3,"Argentina"),
	(4,"Australia"),
	(5,"Austria"),
	(6,"Belgium"),
	(7,"Bosnia and herzegovina"),
	(8,"Brazil"),
	(9,"Bulgaria"),
	(10,"Burkina faso"),
	(11,"Canada"),
	(12,"Chile"),
	(13,"China"),
	(14,"Croatia"),
	(15,"Czech"),
	(16,"Denmark"),
	(17,"England"),
	(18,"Ethiopia"),
	(19,"Finland"),
	(20,"France"),
	(21,"Georgia"),
	(22,"Germany"),
	(23,"Greece"),
	(24,"Hungary"),
	(25,"India"),
	(26,"Iran"),
	(27,"Iraq"),
	(28,"Ireland"),
	(29,"Italy"),
	(30,"Japan"),
	(31,"Korea"),
	(32,"Lebanon"),
	(33,"Lithuania"),
	(34,"Macedonia"),
	(35,"Mauritania"),
	(36,"Mexico"),
	(37,"Mongolia"),
	(38,"Netherlands"),
	(39,"New zealand"),
	(40,"Norway"),
	(41,"Palestine"),
	(42,"Peru"),
	(43,"Philippine"),
	(44,"Poland"),
	(45,"Portugal"),
	(46,"Romania"),
	(47,"Russia"),
	(48,"Scotland"),
	(49,"Senegal"),
	(50,"Serbia"),
	(51,"Slovakia"),
	(52,"South africa"),
	(53,"Spain"),
	(54,"Sri lanka"),
	(55,"Sweden"),
	(56,"Switzerland"),
	(57,"Syria"),
	(58,"Taiwan"),
	(59,"Thailand"),
	(60,"Tunisia"),
	(61,"Turkey"),
	(62,"Uruguay"),
	(63,"Venezuela"),
	(64,"Vietnam"),
	(65,"Yemen"),
	(66,"Zionist entity");

